version: "3.9"

services:
  mysql:
    image: mysql:8-oracle
    container_name: mysql-wallet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: dummypassword
      MYSQL_DATABASE: wallet_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
